export const ADD_INGREDIENT = "ADD_INGREDIENTS"
export const REMOVE_INGREDIENT = "REMOVE_INGREDIENTS"

export const SET_INGREDIENTS_FAIL = "SET_INGREDIENTS_FAIL"
export const SET_INGREDIENTS = "SET_INGREDIENTS"

export const POST_ORDER_START = "POST_ORDER_START"
export const POST_ORDER_SUCCESS = "POST_ORDER_SUCCESS"
export const POST_ORDER_FAIL = "POST_ORDER_FAIL"

export const GET_ORDERS_START = "GET_ORDERS_START"
export const GET_ORDERS_SUCCESS = "GET_ORDERS_SUCCESS"
export const GET_ORDERS_FAIL = "GET_ORDERS_FAIL"
